CREATE TABLE
    IS601_Shop_Categories(
        id int auto_increment PRIMARY KEY,
        name VARCHAR(30) UNIQUE,
        created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )